
export enum Gender {
  Male = 'Masculino',
  Female = 'Femenino',
  Other = 'Otro'
}

export enum Goal {
  LoseWeight = 'Perder grasa',
  GainMuscle = 'Ganar músculo',
  Maintenance = 'Mantenimiento',
  Strength = 'Fuerza máxima',
  Endurance = 'Resistencia muscular',
  Cardio = 'Mejorar resistencia cardiovascular'
}

export enum ActivityLevel {
  Sedentary = 'Sedentario',
  Light = 'Ligero (1-2 días/semana)',
  Moderate = 'Moderado (3-5 días/semana)',
  Active = 'Activo (6-7 días/semana)',
  Athlete = 'Atleta profesional'
}

export enum BodyType {
  Ectomorph = 'Ectomorfo',
  Mesomorph = 'Mesomorfo',
  Endomorph = 'Endomorfo'
}

export interface UserProfile {
  name: string;
  age: number;
  height: number; // cm
  weight: number; // kg
  gender: Gender;
  bodyType?: BodyType;
  goal: Goal;
  activityLevel: ActivityLevel;
  equipment: string[]; // e.g., "Gym", "Dumbbells", "None"
  injuries?: string; // Now includes mechanical impediments description
  
  // Cycle Syncing Fields
  isCycleTracking?: boolean;
  lastPeriodStart?: string; // ISO Date String
  cycleLength?: number; // Default 28
}

export interface UserAccount {
    id: string;
    email: string;
    password: string; // Stored in localstorage (simulated)
    profile?: UserProfile;
}

export interface ExerciseSet {
  weight: number;
  reps: number;
  rpe?: number; // Rate of Perceived Exertion (1-10)
  isWarmup?: boolean;
}

export interface Exercise {
  name: string;
  sets: number;
  reps: string;
  rest: string; // e.g. "60s"
  muscleGroup: string;
  description: string;
  tips: string;
  tempo?: string; // e.g. "3-1-1-0"
  videoQuery: string; // For generating a YouTube search link
  category?: 'warmup' | 'main' | 'cooldown'; // New field for sectioning
  performedSets?: ExerciseSet[]; // For manual/pro logging
  userNotes?: string; // Personal notes for the exercise
}

export interface WorkoutDay {
  dayName: string; // e.g., "Día 1: Tren Superior" or "Lunes"
  focus: string; // e.g., "Pecho y Espalda"
  exercises: Exercise[];
}

export interface MedicalAnalysis {
  severity: 'High' | 'Medium' | 'Low' | 'None'; // Priority classification
  warningTitle?: string; // Short title for the alert
  warningMessage?: string; // Detailed advice regarding the impediment
  modifications: string[]; // List of specific biomechanical adaptations applied (e.g. "Avoid axial loading due to scoliosis")
}

export interface WorkoutPlan {
  title: string;
  description: string;
  frequency: string;
  schedule: WorkoutDay[]; // Changed from single exercises array to weekly schedule
  estimatedDuration: string;
  difficulty: 'Principiante' | 'Intermedio' | 'Avanzado';
  recommendations?: string[];
  
  // Periodization & Scheduling Fields
  durationWeeks: number; // Recommended cycle duration (e.g., 8 weeks)
  cycleDurationAdvice?: string; // Scientific rationale for the duration
  periodizationModel: string; // e.g. "Linear Periodization", "Undulating", "Block"
  progressionGuide: string; // Specific advice on how to overload (e.g. "Increase weight by 2.5% every week")
  
  // Medical & Mechanical Analysis
  medicalAnalysis: MedicalAnalysis;
  
  // Cycle Syncing Info (Generated by AI)
  cyclePhase?: string; 
  
  startDate?: string; // ISO String date when the workout was created/started
}

export interface WorkoutTemplate {
    id: string;
    name: string;
    exercises: Exercise[];
    createdAt: string;
}

export interface Macronutrients {
  protein: number; // grams
  carbs: number;
  fats: number;
  calories: number;
}

export interface Meal {
  name: string;
  description: string;
  ingredients: string[];
  instructions?: string[]; // Step-by-step preparation
  calories: number;
  protein: number;
  carbs: number;
  fats: number;
}

export interface DietDay {
  day: string; // "Lunes", "Martes", etc.
  meals: Meal[];
}

export interface DietPlan {
  title: string;
  summary: string;
  dailyTargets: Macronutrients;
  schedule: DietDay[]; // Weekly schedule
  scientificBasis: string[]; // References/Books/Studies
  hydrationRecommendation: string;
  startDate?: string; // ISO String date when the diet was created/started
}

export interface WorkoutLog {
  id: string;
  date: string; // ISO string
  workoutTitle: string;
  exercisesCompleted: number;
  totalExercises: number;
  durationSeconds: number;
  exercises?: Exercise[]; // Snapshot of exercises performed
}

// --- Gym Admin Types ---
export interface GymMember {
  id: string;
  name: string;
  contactInfo?: string; // Email or Phone number
  contactType?: 'Email' | 'Teléfono';
  joinDate: string;
  plan: 'Mensual' | 'Trimestral' | 'Anual' | 'VIP' | 'Visita';
  status: 'Activo' | 'Inactivo' | 'Pendiente' | 'Vencido';
  lastPaymentDate: string; 
  lastPaymentAmount?: number; // Actual amount paid
  subscriptionEndDate: string; 
  notes?: string;
}

export interface GymEquipment {
  id: string;
  name: string;
  category: string;
  purchaseDate: string;
  status: 'Operativo' | 'Mantenimiento' | 'Fuera de Servicio';
  lastMaintenance: string;
}

export interface GymSubscriptionPlan {
  id: string;
  name: string; // e.g. "Gold Plan"
  price: number;
  durationMonths: number;
  benefits: string[];
}

export interface GymExpense {
  id: string;
  description: string;
  amount: number;
  date: string;
  category: 'Alquiler' | 'Servicios' | 'Mantenimiento' | 'Salarios' | 'Equipo' | 'Marketing' | 'Otros';
}

export type ViewState = 'profile' | 'workout' | 'diet' | 'calendar' | 'medical'; // 'medical' added